# Generated by Django 3.1.1 on 2023-12-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userextra_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='id',
        ),
        migrations.AlterField(
            model_name='userextra',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
