# Generated by Django 3.1.1 on 2023-12-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('username', models.CharField(max_length=100)),
                ('elo_score', models.IntegerField()),
                ('picture_link', models.URLField(max_length=255)),
            ],
        ),
    ]
