# Generated by Django 3.1.1 on 2023-12-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventplayers',
            old_name='total_tites',
            new_name='total_ties',
        ),
    ]
